FROM python:3.11-slim

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements.txt /code/requirements.txt
COPY requirements.train.txt /code/requirements.train.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.train.txt

COPY . .

CMD ["python", "-m", "ml.training.main_train"]
